name: Shell Commands
on: [push]
jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
          - name: echo a string
            run: echo "Hello Anuj Welcome!"

          - name: checkout
            uses: actions/checkout@v1

          - name: List Files
            run: |
                ls -a
                pwd
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
                echo "${{ github.token }}"
          - name: python Commands
            run: |
                import platform
                print
                (platform.processor())
            shell: python